<x-app-layout><x-slot name="header"><h1 class="text-2xl font-bold">{{ $manage ? 'Staff leave & approvals' : 'My leave' }}</h1></x-slot><x-erp-panel>
@if($manage)<a class="underline" href="{{ route('hr.leave.settings') }}">Leave types, allowances & non-working dates</a>@endif
<form method="get" class="flex gap-3 items-end"><label>Balance year<input type="number" name="year" value="{{ $year }}" min="2020" max="2100" class="block rounded border-gray-300"></label><button class="underline py-2">View balances</button></form>
<div class="kw-panel bg-white p-5"><h2 class="font-bold">{{ $year }} leave balances</h2><div class="overflow-x-auto"><table class="w-full text-left"><thead><tr>@if($manage)<th>Staff member</th>@endif<th>Type</th><th>Allowance</th><th>Approved</th><th>Pending</th><th>Available</th></tr></thead><tbody>@forelse($allowances as $allowance)@php($approved=$allowance->usedHalfDays())@php($pending=$allowance->usedHalfDays(['submitted']))<tr class="border-t">@if($manage)<td class="py-3">{{ $allowance->staff->name }}</td>@endif<td>{{ $allowance->type->name }}</td><td>{{ $allowance->half_days/2 }}</td><td>{{ $approved/2 }}</td><td>{{ $pending/2 }}</td><td>{{ ($allowance->half_days-$approved-$pending)/2 }}</td></tr>@empty<tr><td class="py-3" colspan="6">No allowances recorded for this year. HR sets allowances according to the school’s approved policy.</td></tr>@endforelse</tbody></table></div></div>
@if($staff || $manage)<details class="kw-panel bg-white p-5" @if(!$requests->count()) open @endif><summary class="font-bold cursor-pointer">Request leave</summary>
<form action="{{ route('staff.leave.store') }}" method="post" enctype="multipart/form-data" class="grid md:grid-cols-2 gap-4 mt-4">@csrf<input type="hidden" name="submission_key" value="{{ old('submission_key',(string)Illuminate\Support\Str::uuid()) }}">
@if($manage)<label>Employee<select name="staff_profile_id" required class="block w-full rounded border-gray-300">@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected(old('staff_profile_id')==$employee->id)>{{ $employee->name }}</option>@endforeach</select></label>@endif
<label>Leave type<select name="staff_leave_type_id" required class="block w-full rounded border-gray-300"><option value="">Select type</option>@foreach($types as $type)<option value="{{ $type->id }}" @selected(old('staff_leave_type_id')==$type->id)>{{ $type->name }}{{ $type->requires_document ? ' (supporting document required)' : '' }}</option>@endforeach</select></label>
<label>First day<input type="date" name="starts_on" value="{{ old('starts_on') }}" required class="block w-full rounded border-gray-300"></label><label>Last day<input type="date" name="ends_on" value="{{ old('ends_on') }}" required class="block w-full rounded border-gray-300"></label>
<label>Duration<select name="portion" class="block w-full rounded border-gray-300">@foreach(['full'=>'Full days','am'=>'Morning only (one date)','pm'=>'Afternoon only (one date)'] as $value=>$label)<option value="{{ $value }}" @selected(old('portion')===$value)>{{ $label }}</option>@endforeach</select></label>
<label>Supporting document (PDF/JPG/PNG, up to 10 MB)<input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png" class="block w-full"></label>
<label class="md:col-span-2">Reason<textarea name="reason" required maxlength="3000" class="block w-full rounded border-gray-300">{{ old('reason') }}</textarea></label><p class="text-sm md:col-span-2">Days follow the selected leave type’s working calendar. Pending requests reserve allowance. Leave spanning two calendar years must be submitted separately.</p><button class="rounded bg-indigo-700 px-4 py-2 text-white">Submit for approval</button>
</form></details>@else<div class="kw-panel bg-white p-5">Ask HR to link your active staff profile before submitting leave.</div>@endif
<div class="kw-panel bg-white overflow-x-auto"><table class="w-full text-left"><thead><tr><th class="p-3">Employee / leave</th><th>Dates</th><th>Days</th><th>Status</th></tr></thead><tbody>@forelse($requests as $leave)<tr class="border-t"><td class="p-3"><a class="underline" href="{{ route('staff.leave.show',$leave) }}">{{ $leave->staff->name }} · {{ $leave->type->name }}</a></td><td>{{ $leave->starts_on->format('d M Y') }} – {{ $leave->ends_on->format('d M Y') }} ({{ $leave->portion }})</td><td>{{ $leave->half_days/2 }}</td><td>{{ ucfirst($leave->status) }}</td></tr>@empty<tr><td colspan="4" class="p-5">No leave requests yet.</td></tr>@endforelse</tbody></table></div>{{ $requests->links() }}
</x-erp-panel></x-app-layout>
