<x-app-layout><x-slot name="header"><h1 class="text-2xl font-bold">Leave rules & allowances</h1></x-slot><x-erp-panel>
<a class="underline" href="{{ route('hr.leave.index') }}">Leave approvals</a><p>Review the school’s policy before enabling a leave type. Suggested types start disabled, and no statutory entitlements are assumed. Once a type has requests, create a new type to change counting or document rules.</p>
<section class="kw-panel bg-white p-5"><form method="get" class="flex gap-3 items-end"><label>Allowance year<input type="number" name="year" value="{{ $year }}" min="2020" max="2100" class="block rounded border-gray-300"></label><button class="underline py-2">View</button></form><h2 class="font-bold mt-4">Recorded allowances</h2>@forelse($allowances as $allowance)<p class="border-b py-2">{{ $allowance->staff->name }} · {{ $allowance->type->name }} · {{ $allowance->half_days/2 }} days · {{ $allowance->notes }}</p>@empty<p>No allowances recorded for this year.</p>@endforelse</section>
@if($holidays->isNotEmpty())<details class="kw-panel bg-white p-5"><summary>Correct an incorrectly entered non-working date</summary>@foreach($holidays as $holiday)<form method="post" action="{{ route('hr.leave.holidays.remove',$holiday) }}" class="flex flex-wrap gap-3 py-2">@csrf @method('delete')<span>{{ $holiday->date->format('d M Y') }} · {{ $holiday->name }}</span><button class="underline">Remove date</button></form>@endforeach</details>@endif
<details class="kw-panel bg-white p-5"><summary class="font-bold">Add leave type</summary><form method="post" action="{{ route('hr.leave.types.store') }}" class="grid md:grid-cols-2 gap-4 mt-4">@csrf @include('hr.leave.type-fields',['type'=>new \App\Models\StaffLeaveType(['working_days'=>[1,2,3,4,5],'uses_allowance'=>true,'exclude_holidays'=>true])])<button class="rounded bg-indigo-700 text-white px-4 py-2">Add type</button></form></details>
@foreach($types as $type)<details class="kw-panel bg-white p-5"><summary class="font-bold">{{ $type->name }} · {{ $type->active ? 'Enabled' : 'Disabled' }}</summary><form method="post" action="{{ route('hr.leave.types.update',$type) }}" class="grid md:grid-cols-2 gap-4 mt-4">@csrf @method('put') @include('hr.leave.type-fields')<button class="rounded bg-indigo-700 text-white px-4 py-2">Save type</button></form></details>@endforeach
<section class="kw-panel bg-white p-5"><h2 class="font-bold">Set an employee’s total annual allowance</h2><form method="post" action="{{ route('hr.leave.allowances') }}" class="grid md:grid-cols-2 gap-4 mt-3">@csrf<label>Staff<select name="staff_profile_id" required class="block w-full rounded border-gray-300">@foreach($staff as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</select></label><label>Type<select name="staff_leave_type_id" required class="block w-full rounded border-gray-300">@foreach($types->where('uses_allowance',true) as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select></label><label>Year<input name="year" type="number" value="{{ old('year',now()->year) }}" min="2020" max="2100" required class="block w-full rounded border-gray-300"></label><label>Total allowance in days<input name="days" type="number" step="0.5" min="0" max="366" value="{{ old('days') }}" required class="block w-full rounded border-gray-300"></label><label class="md:col-span-2">Policy basis / adjustment reason<textarea name="notes" required class="block w-full rounded border-gray-300">{{ old('notes') }}</textarea></label><button class="rounded bg-indigo-700 text-white px-4 py-2">Set allowance</button></form><p class="text-sm mt-3">This replaces the total allowance for that year, rather than adding days. It cannot be lower than approved and pending leave.</p></section>
<section class="kw-panel bg-white p-5"><h2 class="font-bold">Non-working dates</h2><form method="post" action="{{ route('hr.leave.holidays') }}" class="flex flex-wrap gap-4 mt-3">@csrf<label>Date<input type="date" name="date" required class="block rounded border-gray-300"></label><label>Description<input name="name" required class="block rounded border-gray-300"></label><button class="underline">Save date</button></form><p class="text-sm">Add confirmed public holidays or applicable school closures. Existing requests retain their original counted days.</p><ul class="mt-3">@foreach($holidays as $holiday)<li>{{ $holiday->date->format('d M Y') }} · {{ $holiday->name }}</li>@endforeach</ul></section>
</x-erp-panel></x-app-layout>
