<x-app-layout>
    <x-slot name="header"><div class="mt-16 p-5 kw-page-header rounded-lg flex justify-between"><h2 class="text-2xl font-semibold text-white">{{ $requisition->reference }}</h2><a href="{{ route('teacher.requisitions.index') }}" class="text-white">Back</a></div></x-slot>
    <div class="py-8 kw-soft-section min-h-screen"><div class="max-w-5xl mx-auto sm:px-6 lg:px-8 space-y-5">
        @if(session('success'))<div class="p-4 rounded bg-green-50 text-green-800 border">{{ session('success') }}</div>@endif
        <div class="bg-white kw-panel p-6 grid grid-cols-1 md:grid-cols-2 gap-4 text-sm"><div><span class="text-gray-500">Title:</span> {{ $requisition->title }}</div><div><span class="text-gray-500">Status:</span> {{ $statuses[$requisition->status] ?? $requisition->status }}</div><div><span class="text-gray-500">Priority:</span> {{ ucfirst($requisition->priority) }}</div><div><span class="text-gray-500">Needed by:</span> {{ $requisition->needed_by?->format('d M Y') ?? '-' }}</div><div class="md:col-span-2"><span class="text-gray-500">Reason:</span><div class="whitespace-pre-wrap mt-1">{{ $requisition->reason ?: '-' }}</div></div><div class="md:col-span-2"><span class="text-gray-500">Inventory notes:</span><div class="whitespace-pre-wrap mt-1">{{ $requisition->inventory_notes ?: '-' }}</div></div></div>
        <div class="bg-white kw-panel overflow-x-auto"><table class="min-w-full text-sm divide-y"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">Item</th><th class="px-4 py-3 text-left">Category</th><th class="px-4 py-3 text-left">Quantity</th><th class="px-4 py-3 text-left">Notes</th></tr></thead><tbody class="divide-y">@foreach($requisition->items as $item)<tr><td class="px-4 py-3">{{ $item->item_name }}</td><td class="px-4 py-3">{{ $item->category ?: '-' }}</td><td class="px-4 py-3">{{ $item->quantity }} {{ $item->unit }}</td><td class="px-4 py-3">{{ $item->notes ?: '-' }}</td></tr>@endforeach</tbody></table></div>
        @if(in_array($requisition->status, ['submitted','acknowledged'], true))<form method="POST" action="{{ route('teacher.requisitions.cancel', $requisition) }}" onsubmit="return confirm('Cancel this requisition?');" class="text-right">@csrf @method('PATCH')<button class="px-4 py-2 bg-red-600 text-white rounded-md">Cancel Request</button></form>@endif
    </div></div>
</x-app-layout>
