<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-2xl font-bold text-slate-900 dark:text-white">{{ $run->title }}</h2><p class="text-sm text-slate-500">{{ $run->academicYear?->year_name }}{{ $run->term ? ' · '.$run->term->name : '' }} · {{ ucfirst($run->status) }}</p></div><div class="flex flex-wrap gap-2"><a href="{{ route(Auth::user()->role.'.awards.excel', $run) }}" class="rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white">Download Excel{{ $run->status === 'draft' ? ' (Draft)' : '' }}</a><a href="{{ route(Auth::user()->role.'.awards.certificates-pdf', $run) }}" class="rounded-lg bg-amber-600 px-4 py-2 font-semibold text-white">One PDF (print together)</a><a href="{{ route(Auth::user()->role.'.awards.certificates', $run) }}" class="rounded-lg border border-amber-600 px-4 py-2 font-semibold text-amber-700 dark:text-amber-300">ZIP (separate PDFs)</a><a target="_blank" href="{{ route(Auth::user()->role.'.awards.print', $run) }}" class="rounded-lg border border-[#124E66] px-4 py-2 font-semibold text-[#124E66] dark:border-cyan-300 dark:text-cyan-300">Print list</a>@if($run->status==='draft')<a href="{{ route(Auth::user()->role.'.awards.edit', $run) }}" class="rounded-lg border border-amber-600 px-4 py-2 font-semibold text-amber-700 dark:text-amber-300">Edit award</a><form method="POST" action="{{ route(Auth::user()->role.'.awards.publish',$run) }}" onsubmit="return confirm('Publish these awards to student and parent profiles?')">@csrf<button class="rounded-lg bg-[#124E66] px-4 py-2 font-semibold text-white">Publish awards</button></form><form method="POST" action="{{ route(Auth::user()->role.'.awards.destroy',$run) }}" onsubmit="return confirm('Delete this draft list and all of its generated certificates? This cannot be undone.')">@csrf @method('DELETE')<button class="rounded-lg bg-rose-700 px-4 py-2 font-semibold text-white">Delete draft</button></form>@endif</div></div></x-slot>
    <div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        @if(session('success'))<div class="mb-5 rounded-lg bg-emerald-50 p-4 text-emerald-800">{{ session('success') }}</div>@endif
        <div class="mb-6 grid gap-4 md:grid-cols-4">@foreach([['Status',ucfirst($run->status)],['Recipients',$run->awards->count()],['Cutoff',$run->cutoff_percentage!==null?$run->cutoff_percentage.'%':'Not applicable'],['Basis',$run->generation_summary['calculation_description']??ucfirst($run->type)]] as [$label,$value])<div class="rounded-xl bg-white p-4 shadow dark:bg-brand-800"><div class="text-xs font-bold uppercase text-slate-500">{{ $label }}</div><div class="mt-1 font-bold dark:text-white">{{ $value }}</div></div>@endforeach</div>
        @if($run->status==='draft')<div class="mb-6 rounded-lg border border-amber-300 bg-amber-50 p-4 text-amber-900"><strong>Not published:</strong> final certificates can be downloaded and printed now. Parents cannot see these awards until you publish them.</div>@endif
        <div class="overflow-hidden rounded-xl bg-white shadow dark:bg-brand-800"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50 dark:bg-brand-700"><tr>@foreach(['Position','Student','Class','Subject / Award','Score','Tie-breakers','Certificate',''] as $h)<th class="px-4 py-3 text-left text-xs font-bold uppercase text-slate-500">{{ $h }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-100 dark:divide-brand-700">@foreach($run->awards as $award)<tr><td class="px-4 py-4 font-bold">{{ $award->position ?? '—' }}</td><td class="px-4 py-4"><strong>{{ $award->student_name_snapshot }}</strong><small class="block text-slate-500">{{ $award->admission_no_snapshot }}</small></td><td class="px-4 py-4">{{ $award->class_name_snapshot }}</td><td class="px-4 py-4">{{ $award->subject_name_snapshot ?? $award->award_title }}</td><td class="px-4 py-4">{{ $award->main_score!==null?$award->main_score.'%':'—' }}</td><td class="px-4 py-4 text-xs">@foreach($award->tie_breaker_scores??[] as $tie)<div>{{ $tie['label'] }}: {{ $tie['score']!==null?number_format($tie['score'],2).'%':'—' }}</div>@endforeach</td><td class="px-4 py-4"><a target="_blank" class="font-semibold text-sky-700" href="{{ route(Auth::user()->role.'.awards.certificate',[$run,$award]) }}">A4 certificate</a></td><td class="px-4 py-4">@if($run->status==='draft')<form method="POST" action="{{ route(Auth::user()->role.'.awards.recipients.destroy',[$run,$award]) }}">@csrf @method('DELETE')<button class="text-sm font-semibold text-rose-700">Remove</button></form>@endif</td></tr>@endforeach</tbody></table></div>
        @if($run->status==='draft')<form method="POST" action="{{ route(Auth::user()->role.'.awards.recipients.store',$run) }}" class="mt-6 rounded-xl bg-white p-5 shadow dark:bg-brand-800">@csrf<h3 class="font-bold dark:text-white">Add recipient manually</h3><div class="mt-3 grid gap-3 md:grid-cols-3"><select required name="student_id" class="rounded-lg border-slate-300 dark:bg-brand-700"><option value="">Choose student</option>@foreach($availableStudents as $student)<option value="{{ $student->id }}">{{ $student->user?->name }} · {{ $student->currentClass?->name }}</option>@endforeach</select><input required name="override_reason" class="rounded-lg border-slate-300 dark:bg-brand-700 md:col-span-1" placeholder="Reason for manual addition"><button class="rounded-lg bg-slate-800 px-4 py-2 font-semibold text-white">Add recipient</button></div></form>@endif
        @if(!empty($run->generation_summary['excluded']))
            <details class="mt-6 rounded-xl bg-white p-5 shadow dark:bg-brand-800">
                <summary class="cursor-pointer font-bold">Excluded students ({{ count($run->generation_summary['excluded']) }})</summary>
                <div class="mt-4 space-y-3">
                    @foreach($run->generation_summary['excluded'] as $row)
                        <div class="rounded-lg border border-amber-200 bg-amber-50 p-3 dark:border-amber-800 dark:bg-amber-950/30">
                            <div class="font-semibold text-slate-900 dark:text-white">{{ $row['student_name'] }}</div>
                            <div class="text-sm text-slate-500 dark:text-brand-300">Class: {{ $row['class_name'] ?? 'Class not recorded' }}</div>
                            @if(!empty($row['subject_name']))<div class="text-sm text-slate-500 dark:text-brand-300">Subject: {{ $row['subject_name'] }}</div>@endif
                            <div class="text-sm font-medium text-amber-800 dark:text-amber-300">{{ $row['reason'] }}</div>
                            @if(!empty($row['missing']))
                                <ul class="mt-2 list-disc pl-5 text-sm text-slate-600 dark:text-brand-200">
                                    @foreach($row['missing'] as $missing)
                                        <li>{{ $missing }}</li>
                                    @endforeach
                                </ul>
                            @endif
                        </div>
                    @endforeach
                </div>
            </details>
        @endif
    </div>
</x-app-layout>
