<x-app-layout><x-slot name="header"><h1 class="text-2xl font-bold">{{ $payment->receipt_number ?? 'Pending payment #'.$payment->id }}</h1></x-slot><x-erp-panel>
<a class="underline" href="{{ route('finance.payments.index') }}">All payments</a>
<div class="kw-panel bg-white p-5 space-y-3"><h2 class="text-xl font-bold">P{{ number_format($payment->amount_minor/100,2) }} — {{ ucfirst($payment->status) }}</h2><p>{{ $payment->payer_name }} · {{ $payment->paid_on->format('d M Y') }} · {{ str_replace('_',' ',$payment->method) }}</p><p>Reference: {{ $payment->reference ?? '—' }}</p><p>Email: {{ $payment->payer_email ?? 'Not supplied' }} · {{ str_replace('_',' ',$payment->email_status) }}</p>
@if($payment->reversal_reason)<p class="font-bold">Reversed: {{ $payment->reversal_reason }}</p>@endif
<table class="w-full text-left"><thead><tr><th>Purpose</th><th>Student</th><th>Amount</th></tr></thead><tbody>@foreach($payment->items as $item)<tr class="border-t"><td class="py-3">{{ $item->category_name }} — {{ $item->description }}</td><td>{{ $item->student_name ?? '—' }}</td><td>P{{ number_format($item->amount_minor/100,2) }}</td></tr>@endforeach</tbody></table>
<div class="flex flex-wrap gap-4">@if($payment->status==='pending')<form method="post" action="{{ route('finance.payments.confirm',$payment) }}">@csrf<button class="rounded bg-indigo-700 text-white px-4 py-2">Confirm funds received & issue receipt</button></form>@endif
@if($payment->receipt_number)<a class="underline" href="{{ route('finance.payments.download',$payment) }}">Download receipt PDF</a>@if($payment->payer_email)<form method="post" action="{{ route('finance.payments.email',$payment) }}">@csrf<button class="underline">Email / resend receipt</button></form>@endif @endif</div>
</div>
@if(auth()->user()->isAdmin() && $payment->status!=='reversed')<details class="kw-panel bg-white p-5"><summary>Reverse an incorrect payment</summary><p class="text-sm">This corrects the ledger and retains the original receipt. It does not send money back to the payer.</p><form method="post" action="{{ route('finance.payments.reverse',$payment) }}" class="space-y-3">@csrf<label>Reason<textarea name="reason" required minlength="5" class="block w-full rounded border-gray-300"></textarea></label><button class="rounded bg-red-700 text-white px-4 py-2">Reverse payment</button></form></details>@endif
</x-erp-panel></x-app-layout>
