<x-app-layout>
    <x-slot name="header"><div class="mt-16 p-5 kw-page-header rounded-lg"><h2 class="text-2xl font-semibold text-white">Student Profiles</h2></div></x-slot>
    <div class="py-8 kw-soft-section min-h-screen"><div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-5">
        @if(session('success'))<div class="p-4 rounded bg-green-50 text-green-800 border">{{ session('success') }}</div>@endif
        <div class="bg-white kw-panel p-5"><form method="GET" class="grid grid-cols-1 md:grid-cols-5 gap-3"><input name="search" value="{{ request('search') }}" placeholder="Search name, email, ID/passport" class="md:col-span-2 rounded-md border-gray-300"><select name="class_id" class="rounded-md border-gray-300"><option value="">All classes</option>@foreach($classes as $class)<option value="{{ $class->id }}" @selected(request('class_id')==$class->id)>{{ $class->name }}</option>@endforeach</select><label class="inline-flex items-center gap-2 text-sm"><input type="checkbox" name="incomplete" value="1" @checked(request()->boolean('incomplete'))> Incomplete only</label><button class="px-4 py-2 bg-indigo-600 text-white rounded-md">Filter</button></form></div>
        <div class="bg-white kw-panel overflow-x-auto"><table class="min-w-full divide-y text-sm"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">Student</th><th class="px-4 py-3 text-left">Class</th><th class="px-4 py-3 text-left">Nationality</th><th class="px-4 py-3 text-left">Document</th><th class="px-4 py-3 text-left">Emergency Contact</th><th></th></tr></thead><tbody class="divide-y">
            @forelse($students as $student)
                @php($incomplete = !$student->nationality || !$student->identity_document_type || !$student->identity_document_number || !$student->emergency_contact_name || !$student->emergency_contact_phone)
                <tr class="{{ $incomplete ? 'bg-amber-50' : '' }}"><td class="px-4 py-3"><a class="font-semibold text-indigo-600" href="{{ route('office.students.show', $student) }}">{{ $student->user->name }}</a><div class="text-xs text-gray-500">{{ $student->user->email }}</div></td><td class="px-4 py-3">{{ $student->currentClass->name ?? '-' }}</td><td class="px-4 py-3">{{ $student->nationality ?: '-' }}</td><td class="px-4 py-3">{{ $student->identity_document_number ?: '-' }}</td><td class="px-4 py-3">{{ $student->emergency_contact_name ?: '-' }}<div class="text-xs text-gray-500">{{ $student->emergency_contact_phone }}</div></td><td class="px-4 py-3 text-right"><a class="text-indigo-600" href="{{ route('office.students.edit', $student) }}">Edit</a></td></tr>
            @empty<tr><td colspan="6" class="px-4 py-8 text-center text-gray-500">No students found.</td></tr>@endforelse
        </tbody></table></div>{{ $students->links() }}
    </div></div>
</x-app-layout>
