<x-app-layout>
<x-slot name="header"><h1 class="text-2xl font-bold">Staff & document renewals</h1></x-slot>
<x-erp-panel>
<div class="flex flex-wrap gap-4"><a class="underline" href="{{ route('hr.staff.create') }}">Add staff member</a><a class="underline" href="{{ route('hr.types') }}">Document types & reminders</a></div>
<div class="kw-panel bg-white p-5"><h2 class="text-lg font-bold">{{ $attention->count() }} document requirements need attention</h2><p class="text-sm">Renewal progress does not extend a document’s validity. Missing and unverified documents are included.</p></div>
@if($attention->isNotEmpty())<details class="kw-panel bg-white p-5" open><summary class="font-bold cursor-pointer">Document follow-up</summary><div class="overflow-x-auto"><table class="w-full text-left mt-3"><thead><tr><th>Employee</th><th>Document</th><th>Status</th><th>Expiry</th><th>Renewal</th></tr></thead><tbody>@foreach($attention as $requirement)<tr class="border-t"><td class="py-3"><a class="underline" href="{{ route('hr.staff.show',$requirement->staff_profile_id) }}">{{ $staff->firstWhere('id',$requirement->staff_profile_id)?->name }}</a></td><td>{{ $requirement->type->name }}</td><td>{{ ucwords(str_replace('_',' ',$requirement->status())) }}</td><td>{{ $requirement->currentDocument()?->expires_on?->format('d M Y') ?? '—' }}</td><td>{{ str_replace('_',' ',$requirement->renewal_status) }}</td></tr>@endforeach</tbody></table></div></details>@endif
@if($contracts->isNotEmpty())<div class="kw-panel bg-white p-5"><h2 class="font-bold">Contracts ended or ending within 90 days</h2>@foreach($contracts as $person)<p><a class="underline" href="{{ route('hr.staff.show',$person) }}">{{ $person->name }}</a> · {{ $person->contract_ends_on->format('d M Y') }}</p>@endforeach</div>@endif
<form><label for="search">Search staff</label><input id="search" name="search" value="{{ request('search') }}" class="rounded border-gray-300 mx-2"><button class="underline">Search</button></form>
<div class="kw-panel bg-white overflow-x-auto"><table class="w-full text-left"><thead><tr><th class="p-3">Employee</th><th>Role / department</th><th>Documents</th><th>Contract ends</th><th>Status</th></tr></thead><tbody>
@forelse($staff as $person)<tr class="border-t"><td class="p-3"><a class="underline font-semibold" href="{{ route('hr.staff.show', $person) }}">{{ $person->name }}</a><div class="text-sm">{{ $person->employee_number }}</div></td><td>{{ $person->position }}<div class="text-sm">{{ $person->department }}</div></td><td>{{ $person->requirements->filter(fn($r) => !in_array($r->status(), ['valid','not_applicable']))->count() }} need attention</td><td>{{ $person->contract_ends_on?->format('d M Y') ?? '—' }}</td><td>{{ ucfirst($person->status) }}</td></tr>
@empty<tr><td class="p-6" colspan="5">No staff profiles yet. Add existing teachers and other employees using their current ERP account where available.</td></tr>@endforelse
</tbody></table></div>
</x-erp-panel></x-app-layout>
