<x-app-layout><x-slot name="header"><h1 class="text-2xl font-bold">{{ $staff->name }}</h1><p>{{ $staff->employee_number }} · {{ $staff->position }} · {{ $staff->citizenship }}</p></x-slot><x-erp-panel>
<div class="flex gap-4"><a class="underline" href="{{ route('hr.staff.index') }}">Staff directory</a><a class="underline" href="{{ route('hr.staff.edit',$staff) }}">Edit profile</a></div>
<form method="post" action="{{ route('hr.requirements.store',$staff) }}" class="flex flex-wrap gap-3">@csrf<label>Add document requirement <select name="staff_document_type_id" class="rounded border-gray-300">@foreach($types as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select></label><button class="underline">Add to checklist</button></form>
@foreach($staff->requirements as $requirement)
<section class="kw-panel bg-white p-5 space-y-4"><div><h2 class="font-bold text-lg">{{ $requirement->type->name }}</h2><p>{{ ucwords(str_replace('_',' ',$requirement->status())) }} · Renewal: {{ str_replace('_',' ',$requirement->renewal_status) }}</p><p class="text-sm">{{ $requirement->type->guidance }} Reminders begin {{ $requirement->type->reminder_days }} days before expiry.</p></div>
<details><summary class="cursor-pointer underline">Requirement & renewal follow-up</summary><form method="post" action="{{ route('hr.requirements.update',$requirement) }}" class="grid md:grid-cols-2 gap-3 pt-4">@csrf @method('put')
<label>Required<select name="required" class="block w-full rounded border-gray-300"><option value="1" @selected($requirement->required)>Yes</option><option value="0" @selected(!$requirement->required)>Not applicable</option></select></label>
<label>Reason if not applicable<input name="exception_reason" value="{{ $requirement->exception_reason }}" class="block w-full rounded border-gray-300"></label>
<label>Renewal status<select name="renewal_status" class="block w-full rounded border-gray-300">@foreach(['not_started','preparing','submitted','approved','rejected'] as $value)<option value="{{ $value }}" @selected($requirement->renewal_status===$value)>{{ str_replace('_',' ',$value) }}</option>@endforeach</select></label>
<label>Responsible HR user<select name="responsible_user_id" class="block w-full rounded border-gray-300"><option value="">HR team</option>@foreach($owners as $owner)<option value="{{ $owner->id }}" @selected($requirement->responsible_user_id===$owner->id)>{{ $owner->name }}</option>@endforeach</select></label>
<label>Application date<input type="date" name="application_date" value="{{ $requirement->application_date?->format('Y-m-d') }}" class="block w-full rounded border-gray-300"></label><label>Application reference<input name="application_reference" value="{{ $requirement->application_reference }}" class="block w-full rounded border-gray-300"></label>
<label class="md:col-span-2">Notes<textarea name="notes" class="block w-full rounded border-gray-300">{{ $requirement->notes }}</textarea></label><button class="bg-indigo-700 text-white rounded px-4 py-2">Save follow-up</button></form></details>
<details><summary class="cursor-pointer underline">Upload document / renewal</summary><form method="post" enctype="multipart/form-data" action="{{ route('hr.documents.store',$requirement) }}" class="grid md:grid-cols-2 gap-3 pt-4">@csrf
<label>Document (PDF, JPG or PNG; up to 10 MB)<input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png" required class="block w-full"></label><label>Reference number<input name="reference" class="block w-full rounded border-gray-300"></label><label>Issuer<input name="issuer" class="block w-full rounded border-gray-300"></label><label>Issued on<input name="issued_on" type="date" class="block w-full rounded border-gray-300"></label><label>Expires on<input name="expires_on" type="date" class="block w-full rounded border-gray-300"></label><label>Expiry type<select name="does_not_expire" class="block w-full rounded border-gray-300"><option value="0">Has expiry date</option><option value="1">Does not expire (leave expiry blank)</option></select></label><button class="bg-indigo-700 text-white rounded px-4 py-2">Upload for verification</button></form></details>
<ul class="divide-y">@forelse($requirement->documents as $document)<li class="py-3 flex flex-wrap gap-3 items-center"><a class="underline" href="{{ route('hr.documents.download',$document) }}">{{ $document->original_name }}</a><span>{{ $document->expires_on ? 'Expires '.$document->expires_on->format('d M Y') : 'Does not expire' }} · {{ $document->verified_at ? 'Verified' : 'Awaiting verification' }}</span>@unless($document->verified_at)<form method="post" action="{{ route('hr.documents.verify',$document) }}">@csrf<button class="underline font-semibold">Mark verified</button></form>@endunless</li>@empty<li>No documents uploaded.</li>@endforelse</ul>
</section>@endforeach
</x-erp-panel></x-app-layout>
