<x-app-layout>
    <x-slot name="header"><div class="mt-16 p-5 kw-page-header rounded-lg"><h2 class="text-2xl font-semibold text-white">Class Register Monitor</h2><p class="text-white/80 text-sm">Track class teachers who have not recorded attendance</p></div></x-slot>
    <div class="py-8 kw-soft-section min-h-screen"><div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-5">
        <div class="bg-white kw-panel p-5"><form method="GET" class="grid grid-cols-1 md:grid-cols-4 gap-3"><div><label class="block text-sm text-gray-600">Date</label><input type="date" name="date" value="{{ $selectedDate->toDateString() }}" class="mt-1 w-full rounded-md border-gray-300"></div><div><label class="block text-sm text-gray-600">Academic Year</label><select name="academic_year_id" class="mt-1 w-full rounded-md border-gray-300"><option value="">All years</option>@foreach($academicYears as $year)<option value="{{ $year->id }}" @selected((string)$selectedAcademicYearId===(string)$year->id)>{{ $year->year_name }}</option>@endforeach</select></div><div class="flex items-end gap-2"><button class="px-4 py-2 bg-indigo-600 text-white rounded-md">Load</button><a href="{{ route('register-officer.registers.csv', request()->query()) }}" class="px-4 py-2 bg-slate-700 text-white rounded-md">CSV</a></div></form></div>
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4"><div class="bg-white p-5 rounded-xl border"><p class="text-sm text-gray-500">Classes</p><p class="text-3xl font-bold">{{ $summary['total'] }}</p></div><div class="bg-white p-5 rounded-xl border"><p class="text-sm text-gray-500">Complete</p><p class="text-3xl font-bold text-green-600">{{ $summary['complete'] }}</p></div><div class="bg-white p-5 rounded-xl border"><p class="text-sm text-gray-500">Partial</p><p class="text-3xl font-bold text-amber-600">{{ $summary['partial'] }}</p></div><div class="bg-white p-5 rounded-xl border"><p class="text-sm text-gray-500">Missing</p><p class="text-3xl font-bold text-red-600">{{ $summary['missing'] }}</p></div></div>
        <div class="bg-white kw-panel overflow-x-auto"><table class="min-w-full text-sm divide-y"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">Class</th><th class="px-4 py-3 text-left">Class Teacher</th><th class="px-4 py-3 text-left">Status</th><th class="px-4 py-3 text-left">Recorded</th><th class="px-4 py-3 text-left">P/A/L/E</th><th class="px-4 py-3 text-left">Last Recorded</th></tr></thead><tbody class="divide-y">
            @forelse($rows as $row)
                <tr class="{{ $row['missing'] ? 'bg-red-50' : ($row['partial'] ? 'bg-amber-50' : '') }}"><td class="px-4 py-3 font-semibold">{{ $row['class']->name }}</td><td class="px-4 py-3">{{ $row['teacher'] }}</td><td class="px-4 py-3">@if($row['holiday'])<span class="px-2 py-1 rounded-full bg-amber-100 text-amber-800 text-xs">Holiday: {{ $row['holiday']['title'] }}</span>@elseif($row['complete'])<span class="px-2 py-1 rounded-full bg-green-100 text-green-800 text-xs">Complete</span>@elseif($row['partial'])<span class="px-2 py-1 rounded-full bg-amber-100 text-amber-800 text-xs">Partial</span>@else<span class="px-2 py-1 rounded-full bg-red-100 text-red-800 text-xs">Missing</span>@endif</td><td class="px-4 py-3">{{ $row['recorded_count'] }}/{{ $row['student_count'] }}</td><td class="px-4 py-3">{{ $row['present'] }}/{{ $row['absent'] }}/{{ $row['late'] }}/{{ $row['excused'] }}</td><td class="px-4 py-3">{{ $row['last_recorded_at'] ? \Carbon\Carbon::parse($row['last_recorded_at'])->format('d M Y') : '-' }}</td></tr>
            @empty<tr><td colspan="6" class="px-4 py-8 text-center text-gray-500">No class teacher classes found.</td></tr>@endforelse
        </tbody></table></div>
    </div></div>
</x-app-layout>
